name: "Build"

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

env:
  MESA_VERSION: "25.2.6"

jobs:
  mesa:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-x86_64-mesa
            os: ubuntu-latest
            short_os: linux
            arch: x86_64

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - name: install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: install dependencies
        run: |
          sudo apt-get install -y libdrm-dev byacc flex python3-mako
          pip3 install --user meson

      - name: download mesa
        run: |
          curl -L --retry 5 https://archive.mesa3d.org/mesa-$MESA_VERSION.tar.xz -o mesa-$MESA_VERSION.tar.xz
          tar xf mesa-$MESA_VERSION.tar.xz

      - name: setup
        run: |
          cd mesa-$MESA_VERSION

          meson setup builddir/ --buildtype=release -Dprefix="${PWD}/install/" -Dgallium-drivers=swrast -Dvulkan-drivers=swrast -Dplatforms= -Dglx=disabled

      - name: build
        run: |
          cd mesa-$MESA_VERSION

          meson install -C builddir/

      - name: compress
        run: |
          cd mesa-$MESA_VERSION/install

          tar -cvf ../mesa-$MESA_VERSION-${{ matrix.short_os }}-${{ matrix.arch }}.tar.xz .

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: mesa-${{ env.MESA_VERSION }}/mesa-${{ env.MESA_VERSION }}-${{ matrix.short_os }}-${{ matrix.arch }}.tar.xz
