name: "Build"

permissions:
  contents: write

on:
  - push

jobs:
  swiftshader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout swiftshader
        uses: actions/checkout@v3
        with:
          repository: google/swiftshader
          path: swiftshader

      - name: cmake
        run: |
          cd swiftshader/build

          cmake ..

      - name: build
        run: |
          cd swiftshader/build

          # make -j$(nproc)

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: swiftshader/build/
