name: "Build"

permissions:
  contents: write

on:
  push:
    tags:
      - "build-*"

jobs:
  swiftshader:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-swiftshader
            os: windows-latest
            short_os: windows
            out_dir: Windows
          - name: macos-swiftshader
            os: macos-latest
            short_os: darwin
            out_dir: Darwin
          - name: linux-swiftshader
            os: ubuntu-latest
            short_os: linux
            out_dir: Linux

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - name: install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: checkout swiftshader
        uses: actions/checkout@v3
        with:
          repository: google/swiftshader
          path: swiftshader

      - name: cmake
        run: |
          cd swiftshader/build

          cmake .. -G Ninja
        shell: bash

      - name: build
        run: |
          cd swiftshader/build

          ninja
        shell: bash

      - name: compress
        run: |
          cd swiftshader/build

          tar -cvf swiftshader-${{ matrix.short_os }}.tar.xz ${{ matrix.out_dir }}/*
        shell: bash

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: swiftshader/build/swiftshader-${{ matrix.short_os }}.tar.xz
